#!/bin/bash

if [ -x /usr/bin/yay ]; then
   nb_aur=$(yay -Qua | tee /tmp/aurupdates | wc -l)
   update_command="yay -Syu"
elif [ -x /usr/bin/trizen ]; then
   nb_aur=$(trizen -Qua 2>&1 | cut -d" " -f 2,6,7,8 | sed -e 's/[()]//g' | tee /tmp/aurupdates | wc -l)
   update_command="trizen -Syua"
elif [ -x /usr/bin/pacaur ]; then
   nb_aur=$(pacaur -Qua | awk '$2 == "aur" {print $3 $4 $5 $6}' | tee /tmp/aurupdates | wc -l)
   update_command="pacaur -Syu"
elif [ -x /usr/bin/yaourt ]; then
    nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
    update_command="yaourt -Syua"
else
   nb_aur=0
   update_command="sudo pacman -Syu"
fi

$update_command || read -p 'Press a key to close...'
