#!/bin/bash

. ~/.profile
trap 'rm /tmp/{pacmanupdates,aurupdates} 2>/dev/null' INT TERM QUIT EXIT
nb_pac=$(checkupdates | tee /tmp/pacmanupdates | wc -l)
if [ -f /usr/bin/pacaur ]; then
   nb_aur=$(pacaur -Qua | awk '$2 == "aur" {print $3 $4 $5 $6}' | tee /tmp/aurupdates | wc -l)
elif [ -f /usr/bin/yaourt ]; then
    nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
else
   nb_aur=0
fi


if [ -z "$TERMINAL" ]; then
  if [ "$(which sterminal)" ]; then
    echo "export TERMINAL=\"sterminal\"" >> ~/.profile
    TERMINAL="sterminal"
  elif [ "$(which urxvt)" ]; then
    echo "export TERMINAL=\"urxvt\"" >> ~/.profile
    TERMINAL="urxvt"
  elif [ "$(which termite)" ]; then
    echo "export TERMINAL=\"termite\"" >> ~/.profile
    TERMINAL="termite"
  elif [ "$(which terminator)" ]; then
    echo "export TERMINAL=\"terminator\"" >> ~/.profile
    TERMINAL="terminator"
  elif [ "$(which sakura)" ]; then
    TERMINAL="sakura"
    echo "export TERMINAL=\"sakura\"" >> ~/.profile
  elif [ "$(which lxterminal)" ]; then
    echo "export TERMINAL=\"lxterminal\"" >> ~/.profile
    TERMINAL="lxterminal"
  elif [ "$(which xfce4-terminal)" ]; then
    TERMINAL="xfce4-terminal"
    echo "export TERMINAL=\"xfce4-terminal\"" >> ~/.profile
  elif [ "$(which gnome-terminal)" ]; then
    echo "export TERMINAL=\"gnome-terminal\"" >> ~/.profile
    TERMINAL="gnome-terminal"
  elif [ "$(which konsole)" ]; then
    TERMINAL="konsole"
    echo "export TERMINAL=\"konsole\"" >> ~/.profile
  elif [ "$(which qterminal)" ]; then
    TERMINAL="qterminal"
    echo "export TERMINAL=\"qterminal\"" >> ~/.profile
  elif [ "$(which xterm)" ]; then
    TERMINAL="xterm"
    echo "export TERMINAL=\"xterm\"" >> ~/.profile
  fi
fi

if ((nb_pac>0 || nb_aur>0)); then
  ((nb_aur>0)) && nb_aur="+ ${nb_aur}" && cat /tmp/aurupdates >> /tmp/pacmanupdates
  ((nb_aur==0)) && unset nb_aur
  answer=$(dunstify "You have ${nb_pac} ${nb_aur} updates" "$(cat /tmp/pacmanupdates)" \
   -A Y,"Update now" -A N,Later)
    case $(echo $answer) in
      Y) $TERMINAL -e update-help
        ;;
    *) echo "$answer no match" 
    esac 
else
  dunstify "Your system is up to date" "No packages to update"
fi
