#!/bin/sh
if [ -f /usr/bin/pacaur ]; then
   nb_aur=$(pacaur -Qua | awk '$2 == "aur" {print $3 $4 $5 $6}' | tee /tmp/aurupdates | wc -l)
   update_command="pacaur -Syu"
elif [ -f /usr/bin/yaourt ]; then
    nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
    update_command="yaourt -Syua"
else
   nb_aur=0
   update_command="sudo pacman -Syu"
fi

$update_command || read -p 'Press a key to close...'