#!/bin/bash

trap 'rm /tmp/{pacmanupdates,aurupdates} 2>/dev/null' INT TERM QUIT EXIT

if ! $(ping -c 3 google.com >> /dev/null 2>&1); then
	exit
elif [[ -e /run/miso/bootmnt ]]; then
	exit
fi

nb_pac=$(checkupdates | tee /tmp/pacmanupdates | wc -l)
if [ -f /usr/bin/pacaur ]; then
   nb_aur=$(pacaur -Qua | awk '$2 == "aur" {print $3 $4 $5 $6}' | tee /tmp/aurupdates | wc -l)
   update_command="pacaur -Syu"
elif [ -f /usr/bin/yaourt ]; then
    nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
    update_command="yaourt -Syua"
else
   nb_aur=0
   update_command="sudo pacman -Syu"
fi

if ((nb_pac>0 || nb_aur>0)); then
  ((nb_aur>0)) && nb_aur="+ ${nb_aur}"
  ((nb_aur==0)) && unset nb_aur
  cat /tmp/pacmanupdates 
  cat /tmp/aurupdates
fi

# Check if the running kernel is eol
if ! $(pacman -Ssq $(mhwd-kernel -li | awk '/ \* / {print $2}' | head -n1) &> /dev/null); then 
	msm=$(dunstify -A manjaro-settings-manager,ACCEPT -A true,DECLINE "Your kernel is no longer supported" "Please change kernel with Manjaro Settings Manager")
	[[ "$msm" == "manjaro-settings-manager" ]] && manjaro-settings-manager &> /dev/null &
fi

# Branch
if ! $(grep -q "^Branch" /etc/pacman-mirrors.conf); then 
  branch=stable
  capital_branch=Stable
else
  branch=$(awk '/Branch =/{print $3}' /etc/pacman-mirrors.conf)
  capital_branch=$(echo $branch | sed 's/\b[a-z]/\u&/g')
fi
# timestamp update announcements. 
last_annoncement=$(curl https://forum.manjaro.org/c/announcements/"$branch"-updates.rss 2> /dev/null | awk '/<title>/' | awk -v br="$capital_branch" '/\[br Update\]/{print $3}' | head -n1)
# timestamp of last update
last_update=$(awk '/upgrade/ {print $1}' /var/log/pacman.log | sed 's/\[//' | tail -n1)
if [[ $last_annoncement > $last_update ]]; then
	answer=$(dunstify -A terminal_update,YES -A true,NO "Update requires user input. Advice in forum announcements." "Run next update in terminal?")
	case $(echo answer) in
	terminal_update)
		touch /tmp/.manual_update
		;;
	*)
		true
		;;
	esac
fi
