#!/bin/bash

trap 'rm /tmp/{pacmanupdates,aurupdates} 2>/dev/null' INT TERM QUIT EXIT
nb_pac=$(checkupdates | tee /tmp/pacmanupdates | wc -l)
if [ -f /usr/bin/pacaur ]; then
   nb_aur=$(pacaur -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
   update_command="pacaur -Syu"
elif [ -f /usr/bin/yaourt ]; then
    nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
    update_command="yaourt -Syua"
else
   nb_aur=0
   update_command="sudo pacman -Syu"
fi



if [ -z "$TERMINAL" ]; then
  if [ "$(which sterminal)" ]; then
	  echo "export TERMINAL=\"sterminal\"" >> ~/.profile
	  TERMINAL="sterminal -e"
  elif [ "$(which urxvt)" ]; then
	  echo "export TERMINAL=\"urxvt\"" >> ~/.profile
	  TERMINAL="urxvt -e"
  elif [ "$(which termite)" ]; then
	  echo "export TERMINAL=\"termite\"" >> ~/.profile
	  TERMINAL="termite -e"
  elif [ "$(which terminator)" ]; then
	  echo "export TERMINAL=\"terminator\"" >> ~/.profile
	  TERMINAL="terminator -e"
  elif [ "$(which sakura)" ]; then
	  TERMINAL="sakura -e"
	  echo "export TERMINAL=\"sakura\"" >> ~/.profile
  elif [ "$(which lxterminal)" ]; then
	  echo "export TERMINAL=\"lxterminal\"" >> ~/.profile
	  TERMINAL="lxterminal -e"
  elif [ "$(which xfce4-terminal)" ]; then
	  TERMINAL="xfce4-terminal -e"
	  echo "export TERMINAL=\"xfce4-terminal\"" >> ~/.profile
  elif [ "$(which gnome-terminal)" ]; then
	  echo "export TERMINAL=\"gnome-terminal\"" >> ~/.profile
	  TERMINAL="gnome-terminal -e"
  elif [ "$(which konsole)" ]; then
	  TERMINAL="konsole -e"
	  echo "export TERMINAL=\"konsole\"" >> ~/.profile
  elif [ "$(which qterminal)" ]; then
	  TERMINAL="qterminal -e"
	  echo "export TERMINAL=\"qterminal\"" >> ~/.profile
  elif [ "$(which xterm)" ]; then
	  TERMINAL="xterm -e"
	  echo "export TERMINAL=\"xterm\"" >> ~/.profile
  fi
fi

if ((nb_pac>0 || nb_aur>0)); then
  ((nb_aur>0)) && nb_aur="+ ${nb_aur}"
  ((nb_aur==0)) && unset nb_aur
  dunstify "You have ${nb_pac} ${nb_aur} updates" "$(cat /tmp/pacmanupdates) \n$(cat /tmp/aurupdates)" \
   -A YES,"Update now" -A NO,Later | read answer
    case $answer in
    	YES) $TERMINAL -e $update_command
    		;;
    	NO) true
			;;
    esac 
else
  dunstify "Your system is up to date" "No packages to update"
fi
